### ISSUE TITLE
Unable to build Gridsome site

### ISSUE THREAD

**Issue by lindsaykwardell** [Stegosource/vuetensils#71]
Ran into an issue building my Gridsome site with the latest version of Vuetensils (0.5.6). For reference, I am importing VToggle on one page. 

During the build, I am getting the following error:

```
document is not defined
    at addStyle (node_modules/vuetensils/dist/vuetensils.esm.js:762:0)
    at assets/js/vendors~page--src--pages--policies-vue.dc0da65c.js:767:42
    at a.__vue_inject_styles__$e (node_modules/vuetensils/dist/vuetensils.esm.js:2964:0)
    at a.hook (node_modules/vuetensils/dist/vuetensils.esm.js:198:0)
    at Ft (node_modules/vue/dist/vue.runtime.common.prod.js:6:11191)
    at Ze (node_modules/vue/dist/vue.runtime.common.prod.js:6:25133)
    at a.e._init (node_modules/vue/dist/vue.runtime.common.prod.js:6:32564)
    at new a (node_modules/vue/dist/vue.runtime.common.prod.js:6:30340)
    at Vi (node_modules/vue-server-renderer/build.prod.js:1:66307)
    at io (node_modules/vue-server-renderer/build.prod.js:1:70537)
```

This is the function from the top of the stack trace:

```
function addStyle(id, css) {
    var group = isOldIE ? css.media || 'default' : id;
    var style = styles[group] || (styles[group] = { ids: new Set(), styles: [] });
    if (!style.ids.has(id)) {
        style.ids.add(id);
        var code = css.source;
        if (css.map) {
            // https://developer.chrome.com/devtools/docs/javascript-debugging
            // this makes source maps inside style tags work properly in Chrome
            code += '\n/*# sourceURL=' + css.map.sources[0] + ' */';
            // http://stackoverflow.com/a/26603875
            code +=
                '\n/*# sourceMappingURL=data:application/json;base64,' +
                    btoa(unescape(encodeURIComponent(JSON.stringify(css.map)))) +
                    ' */';
        }
        if (!style.element) {
            style.element = document.createElement('style');
            style.element.type = 'text/css';
            if (css.media)
                { style.element.setAttribute('media', css.media); }
            if (HEAD === undefined) {
                HEAD = document.head || document.getElementsByTagName('head')[0];
            }
            HEAD.appendChild(style.element);
        }
        if ('styleSheet' in style.element) {
            style.styles.push(code);
            style.element.styleSheet.cssText = style.styles
                .filter(Boolean)
                .join('\n');
        }
        else {
            var index = style.ids.size - 1;
            var textNode = document.createTextNode(code);
            var nodes = style.element.childNodes;
            if (nodes[index])
                { style.element.removeChild(nodes[index]); }
            if (nodes.length)
                { style.element.insertBefore(textNode, nodes[index]); }
            else
                { style.element.appendChild(textNode); }
        }
    }
}
```
I cannot find this function in the code base, so I'm not sure where it's getting called or why.

EDIT: As a follow-up, when I copy the VToggle component into my own codebase, point to it instead of Vuetensils, and run the build script, there are no errors.

**Comment by Stegosource** [comment]
This is probably something to do with SSR. It's on my todo list to test component for SSR support more thoroughly. 

It's not a solution, but a possible workaround is to wrap the VToggle component in Gridsome's `<ClientOnly>` component so the server does not try to render it.

Can you try that and let me know if it works?

**Comment by lindsaykwardell** [comment]
Looks like that worked fine.

I'm still a bit confused though. When I copy/paste the VToggle component (and the randomString function for it) into my code, there's no issue. Where is the addStyle function even coming from?

**Comment by Stegosource** [comment]
I'm not sure why it works when you copy/paste, but the `addStyle` function is probably the result of the Rollup bundling the original source. I'm going to close this issue as it's still part of my other task of looking into SSR support better.
